---
title: "MetaDeath"
author: "SHAHEEN'S"
date: '2022-06-17'
output: html_document
---


#loading packages 

```{r}
library(tidyverse)
library(readxl)
library(dmetar)
library(meta)
library(janitor)
library(grid)
library(netmeta)
```


#Loading data



```{r}
Alteplase <- read_excel("~/Library/CloudStorage/OneDrive-AlexandriaUniversity/Alteplase/Alteplase.xlsx", sheet = "MetaDeath") %>% as_tibble() %>% clean_names()
Alteplase$event_a1 = as.numeric(Alteplase$event_a1)
```


#Meta analysis

```{r}

mRS90exc <- metabin(event.e = event_t1, 
                 n.e = n_t1,
                 event.c = event_a1,
                 n.c = n_a1,
                 studlab = name,
                 data = Alteplase,
                 sm = "RD",
                 method = "MH",
                 MH.exact = TRUE,
                 fixed = TRUE,
                 random = FALSE,
                 method.tau = "PM",
                 hakn = TRUE,
                 title = "Alteplase ")


summary(mRS90exc)
forest.meta(mRS90exc,fontsize=7)
grid.text("Alteplase Vs Tenecteplase", .5, .9, gp=gpar(cex=1.3))

```


```{r}

#Sub Thromboectomy
metasubectomy = update.meta(mRS90exc, 
            subgroup = thrombectomy)
forest(metasubectomy,fontsize=7)
summary(metasubectomy)
forest(update.meta(metasubectomy, exclude = 5),fontsize=7)
```

```{r}
#Sub Dose
metasubdose = update.meta(mRS90exc, 
            subgroup = dose)
forest(metasubdose,fontsize=7)
summary(metasubdose)
forest(update.meta(metasubdose, exclude = 5),fontsize=7)

```

```{r}
#Sub NIHSS
metasubNIHSS = update.meta(mRS90exc, 
            subgroup = nihss)
forest(metasubNIHSS,fontsize=7)
summary(metasubNIHSS)
forest(update.meta(metasubNIHSS, exclude = 5),fontsize=7)

```


```{r}
#Sub time
metasubtime = update.meta(mRS90exc, 
            subgroup = stroke_onset_to_thrombolysis)
forest(metasubtime,fontsize=7)
summary(metasubNIHSS)
forest(update.meta(metasubtime, exclude = 5),fontsize=7)
```



```{r}
#sensitivity analysis 
mRS90exc.n <- update.meta(mRS90exc,k.min = 7, prediction = TRUE) 
summary(mRS90exc.n)
find.outliers(mRS90exc.n) #brute force approach 
m.gen.inf <- InfluenceAnalysis(mRS90exc.n, random = TRUE) # leave-one-out method
m.gen.inf
names(m.gen.inf)
plot(m.gen.inf) ##Baujat plots
plot(m.gen.inf$BaujatPlot)
plot(m.gen.inf$ForestEffectSize)
plot(m.gen.inf$ForestI2)
plot(m.gen.inf, "influence")
new_meta = update.meta(mRS90exc.n, exclude = 5)  
summary(new_meta)
forest.meta(new_meta,fontsize=7)

```


```{r}
#Bias
eggers.test(mRS90exc.n)
metabias(mRS90exc, k.min = 7 , method.bias = "linreg")

# Produce funnel plot
col.contour = c("gray75", "gray85", "gray95")
ld <- c("p < 0.1", "p < 0.05", "p < 0.01")

funnel.meta(mRS90exc,
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab = TRUE)
legend(x = .2, y = 0.0029, 
       legend = ld, fill = col.contour)

title("Contour-Enhanced Funnel Plot (Alteplase Vs Tenecteplase)")

funnel.meta(mRS90exc,
            studlab = TRUE)
title("Funnel Plot (Alteplase Vs Tenecteplase)")
```





```{r}
#Bias analysis using Duval & Tweedie trim and fill method

# Using all studies
tf <- trimfill(mRS90exc)

# Analyze with outliers removed
tf.no.out <- trimfill(update(mRS90exc, 
                             subset = -c(2)))
summary(tf)
summary(tf.no.out)

# Define fill colors for contour
contour <- c(0.9, 0.95, 0.99)
col.contour <- c("gray75", "gray85", "gray95")
ld <- c("p < 0.1", "p < 0.05", "p < 0.01")


# Contour-enhanced funnel plot (full data)
funnel.meta(tf, 
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab = TRUE)
legend(x = .2, y = 0.0029, 
       legend = ld, fill = col.contour)
title("Funnel Plot (Trim & Fill Method)")

# Contour-enhanced funnel plot (outliers removed)
funnel.meta(tf.no.out, 
            contour = c(0.9, 0.95, 0.99),
            col.contour = col.contour,
            studlab = TRUE)
legend(x = .2, y = 0.0029, 
       legend = ld, fill = col.contour)
title("Funnel Plot (Trim & Fill Method)")
```




#Network meta analysis of doses

#Loading data

```{r}
netdata <- read_excel("~/Library/CloudStorage/OneDrive-AlexandriaUniversity/Alteplase/Alteplase.xlsx", sheet = "NetExcellent") %>% as_tibble() %>% clean_names()
names(netdata)
```


```{r}
p1 <- pairwise(list(treatment_a ,treatment_t10 ,treatment_t25 ,treatment_t40),
               n = list(n_a, n_t10, n_t25 ,n_t40),
               event = list(event_a, event_t10, event_t25, event_t40),
               data = netdata, studlab = name,
                     sm = "RD",
                     fixed = TRUE,
                     random = FALSE,
                reference.group = "alteplase")
m.netmeta <- netmeta(p1)
summary(m.netmeta)
decomp.design(m.netmeta)
# Show treatment order (shortened labels)
m.netmeta$trts
netrank(m.netmeta, small.values = "good")

```


```{r}
library(rgl)
netgraph(m.netmeta, dim = "3d")
netgraph(m.netmeta)
d.evidence <- direct.evidence.plot(m.netmeta)
plot(d.evidence)

# Produce effect table
netleague <- netleague(m.netmeta, 
                       bracket = "(", # use round brackets
                       digits=2)      # round to two digits


netleague
netheat(m.netmeta,nchar.trts =5 )
netheat(m.netmeta, random = TRUE, nchar.trts =5)
forest(m.netmeta)
netsplit(m.netmeta)
options(width = 20)
netsplit(m.netmeta) %>% forest(fontsize=10)
```

















